# Board: Generic ESP32-S2 Board (Generic)
# Definition: definitions/boards/generic-esp32s2/manifest.yaml

esphome:
  name: boiler-monitor
  friendly_name: Boiler Monitor

esp32:
  variant: ESP32
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret boilermon__encryption_key
ota:
  - platform: esphome
    password: !secret boilermon__ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mdns:

time:
  platform: homeassistant

one_wire:
  - platform: gpio
    pin: GPIO13

i2c:
  - scl: GPIO22
    sda: GPIO21

sensor:
  - platform: adc
    pin: GPIO36
    id: boiler_pump_adc
    accuracy_decimals: 4
    internal: true
    attenuation: 12db
    samples: 64

  - platform: adc
    pin: GPIO39
    id: circ_pump_adc
    accuracy_decimals: 4
    internal: true
    attenuation: 12db
    samples: 64

  - platform: adc
    pin: GPIO34
    id: dhw_pump_adc
    accuracy_decimals: 4
    internal: true
    attenuation: 12db
    samples: 64

  - platform: ct_clamp
    sensor: boiler_pump_adc
    id: boiler_pump_current
    name: "Boiler Pump Current"
    entity_category: diagnostic
    update_interval: 5s
    accuracy_decimals: 3
    filters:
      - calibrate_linear:
          datapoints:
          - 0.0032 -> 0.0
          - 0.0100 -> 0.138
      - lambda: |-
          // ignore readings below .1A
          if (x > 0.1){ 
            return x;
          } else {
            return 0.0;
          }

  - platform: ct_clamp
    sensor: circ_pump_adc
    id: circ_pump_current
    name: "Circulator Pump Current"
    entity_category: diagnostic
    update_interval: 5s
    accuracy_decimals: 3
    filters:
      - calibrate_linear:
          datapoints:
          - 0.0032 -> 0.0
          - 0.0100 -> 0.138
      - lambda: |-
          // ignore readings below .1A
          if (x > 0.1){ 
            return x;
          } else {
            return 0.0;
          }

  - platform: ct_clamp
    sensor: dhw_pump_adc
    id: dhw_pump_current
    name: "DHW Pump Current"
    entity_category: diagnostic
    update_interval: 5s
    accuracy_decimals: 3
    filters:
      - calibrate_linear:
          datapoints:
          - 0.0032 -> 0.0
          - 0.0100 -> 0.138
      - lambda: |-
          // ignore readings below .1A
          if (x > 0.1){ 
            return x;
          } else {
            return 0.0;
          }

  - platform: uptime
    name: "Uptime"
    id: boilermon_uptime

  - platform: wifi_signal
    name: "RSSI"
    icon: "mdi:wifi-arrow-up-down"

  - platform: dallas_temp
    name: "Boiler Air Intake"
    index: 0
    update_interval: 5s

  - platform: dallas_temp
    name: "Boiler Inlet"
    index: 1
    update_interval: 5s

  - platform: dallas_temp
    name: "Boiler Outlet"
    index: 2
    update_interval: 5s

  - platform: dallas_temp
    name: "DHW Tank"
    index: 3
    update_interval: 5s

  - platform: dallas_temp
    name: "Boiler Exhaust"
    index: 4
    update_interval: 5s

  - platform: aht10
    update_interval: 30s
    variant: AHT20
    humidity:
      name: Ambient Humidity
      icon: "mdi:water-percent"
    temperature:
      name: Ambient Temperature
      icon: "mdi:home-thermometer"

binary_sensor:
  - platform: template
    name: "Boiler Pump State"
    device_class: running
    icon: "mdi:water-boiler"
    lambda: |-
      static bool last = false;
      float a = id(boiler_pump_current).state;
      if (a > 0.5) last = true;
      if (a < 0.3) last = false;
      return last;

  - platform: template
    name: "Circulator Pump State"
    device_class: running
    icon: "mdi:restart"
    lambda: |-
      static bool last = false;
      float a = id(circ_pump_current).state;
      if (a > 0.5) last = true;
      if (a < 0.3) last = false;
      return last;

  - platform: template
    name: "DHW Pump State"
    device_class: running
    icon: "mdi:water-pump"
    lambda: |-
      static bool last = false;
      float a = id(dhw_pump_current).state;
      if (a > 0.5) last = true;
      if (a < 0.3) last = false;
      return last;

  - platform: gpio
    name: Zone 1 Thermostat
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
      inverted: true
    icon: "mdi:numeric1-circle"
    device_class: heat

  - platform: gpio
    name: Zone 2 Thermostat
    pin:
      number: GPIO18
      mode:
        input: true
        pullup: true
      inverted: true
    icon: "mdi:numeric2-circle"
    device_class: heat

  - platform: gpio
    name: Zone 3 Thermostat
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: true
      inverted: true
    icon: "mdi:numeric3-circle"
    device_class: heat

  - platform: gpio
    name: Zone 4 Thermostat
    pin:
      number: GPIO17
      mode:
        input: true
        pullup: true
      inverted: true
    icon: "mdi:numeric4-circle"
    device_class: heat

text_sensor:
  - platform: template
    name: "Boiler Pump Speed"
    update_interval: 5s
    icon: "mdi:water-boiler"
    entity_category: diagnostic
    lambda: |-
        float a = id(boiler_pump_current).state;
        static std::string last_value = "";
        std::string new_value;

        if (a > .71) {
          new_value = "High";
        } else if (a > .62) {
          new_value = "Medium";
        } else if (a > .51) {
          new_value = "Low";
        } else {
          new_value = "Off";
        }

        if (new_value != last_value) {
          last_value = new_value;
          return new_value;
        } else {
          return {};
        }

  - platform: template
    name: "Circulator Pump Speed"
    update_interval: 5s
    icon: "mdi:restart"
    entity_category: diagnostic
    lambda: |-
        float a = id(circ_pump_current).state;
        static std::string last_value = "";
        std::string new_value;

        if (a > .71) {
          new_value = "High";
        } else if (a > .62) {
          new_value = "Medium";
        } else if (a > .51) {
          new_value = "Low";
        } else {
          new_value = "Off";
        }

        if (new_value != last_value) {
          last_value = new_value;
          return new_value;
        } else {
          return {};
        }

  - platform: template
    name: "DHW Pump Speed"
    update_interval: 5s
    icon: "mdi:water-pump"
    entity_category: diagnostic
    lambda: |-
        float a = id(dhw_pump_current).state;
        static std::string last_value = "";
        std::string new_value;

        if (a > .71) {
          new_value = "High";
        } else if (a > .62) {
          new_value = "Medium";
        } else if (a > .51) {
          new_value = "Low";
        } else {
          new_value = "Off";
        }

        if (new_value != last_value) {
          last_value = new_value;
          return new_value;
        } else {
          return {};
        }

button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic
    icon: "mdi:restart-alert"
